{
 "title": "Nobreak-01",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Voltagem da rede eletrica",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Nobreak/Eletricidade" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Morroc" },
     "item": { "filter": "Voltagem rede eletrica" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Carga estimada",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Nobreak/Eletricidade" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Morroc" },
     "item": { "filter": "Carga estimada" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nivel da  Bateria",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Nobreak/Bateria" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Morroc" },
     "item": { "filter": "Nivel bateria" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Voltagem da Bateria",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Nobreak/Bateria" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Morroc" },
     "item": { "filter": "Voltagem bateria" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Nobreak/Eletricidade" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Morroc" },
     "item": { "filter": "Voltagem rede eletrica" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}